name: Dependabot Auto-Merge
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  approve-and-auto-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      # Simulate this action being in the queue to start and running after CI
      - name: Sleep for 180 seconds
        run: sleep 180s
        shell: bash
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          merge-method: merge
          use-github-auto-merge: true
          target-development: 'major'
          target-production: 'major'

