name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          merge-method: squash
          use-github-auto-merge: true
          target-development: 'major'
          target-production: 'minor'

